version: "3.8"

services:
  db:
    image: postgres
    container_name: leaderboard-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build:
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - WAL_PATH=/usr/src/app/wal.log
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./wal.log:/usr/src/app/wal.log
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
